name: Deploy

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  workflow_call:
    inputs:
      identity_pool:
        required: true	
        type: string
      identity_sa:
        required: true
        type: string
      image:
        required: true
        type: string
      name:
        required: true
        type: string
      region:
        required: true
        type: string
  

# Down scope as necessary via https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token

jobs:
  run-deploy:
    permissions:
      id-token: write # This is required for requesting the JWT
    name: Run deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3


      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          create_credentials_file: 'true'
          workload_identity_provider: ${{inputs.identity_pool}}
          service_account: ${{inputs.identity_sa}}

      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'
  
      # Build and push image to Google Container Registry
      - name: Build
        run: gcloud builds submit --tag ${{inputs.image}}

      # deploy app to Cloud Run
      - name: Deploy
        run: |-
         gcloud run deploy ${{inputs.name}} \
         --platform managed \
         --region ${{inputs.region}} \
         --allow-unauthenticated \
         --image ${{inputs.image}}
