name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      environment:
        required: true
        type: string


# Down scope as necessary via https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token

jobs:
  deploy:
    name: CI
    environment: ${{inputs.environment}}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{inputs.node_version}}

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Cache firebase emulators
        uses: actions/cache@v4
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('~/.cache/firebase/emulators/**') }}

      - name: Install dependencies
        run: pnpm install

      - name: Install Firebase Tools
        run: pnpm i -g firebase-tools@10.9.2

      - name: Build
        run: pnpm build

      - name: Run tests
        run: firebase emulators:exec --only firestore,pubsub 'pnpm test:ci'

      - name: Update Coverage Badge
        run: npx update-badge
